version: "3.7"
services:
  db:
    image: mysql
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd+
    ports:
      - 3306:3306
  flyway:
    image: flyway/flyway
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - db
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd+ -connectRetries=60 -X migrate
  nodejs:
    image: node
    volumes:
      - ./nodejs:/var/lib/nodejs
    working_dir: /var/lib/nodejs
    restart: always
#    depends_on:
#      - db
#    command: npm install run start
    command: bash -c "./wait-for-it.sh db:3306 -- npm install && npm run start"
#    ports:
#      - 1234:1234
#      - 1235:1235
# TODO mysql variables
#    environment:
#      - MONGO_USERNAME=$MONGO_USERNAME
#      - MONGO_PASSWORD=$MONGO_PASSWORD
#      - MONGO_HOSTNAME=db
#      - MONGO_PORT=$MONGO_PORT
#      - MONGO_DB=$MONGO_DB
#    networks:
#      - app-network

