version: "3.7"
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd+ -connectRetries=60 -X migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd+
    ports:
      - 3306:3306
  nodejs:
    image: node
# TODO wait.sh instead of depends_on
# command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js
# "dev" script is defined in package.json under "scripts" section.
    command: npm run dev
    depends_on:
      - db
    restart: always
    volumes:
      - ./nodejs:/var/lib/nodejs
    working_dir: /var/lib/nodejs
    ports:
      - 1234:1234
      - 1235:1235
# TODO mysql variables
#    environment:
#      - MONGO_USERNAME=$MONGO_USERNAME
#      - MONGO_PASSWORD=$MONGO_PASSWORD
#      - MONGO_HOSTNAME=db
#      - MONGO_PORT=$MONGO_PORT
#      - MONGO_DB=$MONGO_DB
#    networks:
#      - app-network

