version: "3.7"
services:
  mysql:
    image: mysql
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    networks:
      - docker_xxx
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd+
#      - MYSQL_DATABASE=database
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=passwd
  flyway:
    depends_on:
      - mysql
    image: flyway/flyway
    volumes:
      - ./flyway:/flyway/sql
    networks:
      - docker_xxx
    command: -url=jdbc:mysql://mysql -schemas=myschema -user=root -password=P@ssw0rd+ -connectRetries=60 -X migrate
  nodejs:
    image: node
    volumes:
      - ./nodejs:/var/lib/nodejs
    working_dir: /var/lib/nodejs
    networks:
      - docker_xxx
    ports:
      - "3000:3000"
      - "8787:8787"
    command: bash -c './wait-for-it.sh mysql:3306 -- npm start'
    environment:
      - PORT=3306
      - DATABASE_HOST=mysql
      - DATABASE_PASSWORD=P@ssw0rd+
networks:
  docker_xxx:
    driver: bridge