version: "3.7"
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd+ -connectRetries=60 migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd+
    ports:
      - 3306:3306
